"""backup user + session

Revision ID: 21902d38da01
Revises: 719948de3c8c
Create Date: 2024-11-19 09:48:56.994591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21902d38da01'
down_revision: Union[str, None] = '719948de3c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_session', ['id'])
    op.create_unique_constraint(None, 'auth_user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user', type_='unique')
    op.drop_constraint(None, 'auth_session', type_='unique')
    # ### end Alembic commands ###
