"""retry-migration - user | session - models

Revision ID: 719948de3c8c
Revises: 5c660d32f15a
Create Date: 2024-11-18 15:19:39.156046

"""

from typing import Sequence, Union

from api.database.database import UTCDateTime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "719948de3c8c"
down_revision: Union[str, None] = "5c660d32f15a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("email_verification_code", sa.String(length=32), nullable=True),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("registration", UTCDateTime(), nullable=True),
        sa.Column("last_login", UTCDateTime(), nullable=True),
        sa.Column("last_name_change", UTCDateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("admin", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("_tags", sa.String(length=550), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column("street", sa.String(length=256), nullable=True),
        sa.Column("zip_code", sa.String(length=16), nullable=True),
        sa.Column("city", sa.String(length=64), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("email_verification_code"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("name"),
        mysql_collate="utf8mb4_bin",
    )
    op.create_table(
        "auth_session",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("device_name", sa.Text(), nullable=True),
        sa.Column("last_update", UTCDateTime(), nullable=True),
        sa.Column("refresh_token", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("refresh_token"),
        mysql_collate="utf8mb4_bin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_session")
    op.drop_table("auth_user")
    # ### end Alembic commands ###
